[Sleep]
AfterRead=10
AfterWriteSignals=5
AfterWriteUART=40
AfterAll=10

; Порядок выполнения функций:
; 1. readSignalsDevice()
;     Sleep(AfterRead);
; 2. dataExchangeInputs();
;
; 3. dataExchangeOutputs();
; 4. writeSignalsDevice();
;     Sleep(AfterWriteSignals);
; 5. writeUARTDevice();
;     Sleep(AfterWriteUART);
; Sleep(AfterAll)
